### ISSUE TITLE
If there is neither `wakatime`, nor `wakatime-cli.exe`, download and install it

### ISSUE THREAD

**Issue by Pozitrone** [Pozitrone/WakaTimeForUE4#14]
I already have about half of the code for this, so I will handle it to the end.

**Comment by simonSlamka** [comment]
Make sure you place it in the ~/.wakatime/wakatime-cli dir.

**Comment by simonSlamka** [comment]
Need my help with anything else?

**Comment by Pozitrone** [comment]
Don't think there is anything at the moment, but thank you :)

**Comment by Pozitrone** [comment]
done in 38c779f9c5473a2c4252ee736167fb4ec502110c
