### ISSUE TITLE
Wakatime icon is not rendered in Toolbar correctly

### ISSUE THREAD

**Issue by yourchev** [Pozitrone/WakaTimeForUE4#2]
ZIP archive is named _WakaTimeForUE4-main_ or _WakaTimeForUE4-release_ after downloading. So if user does not pay too much attention to folder name described in README file and just unpack archive and copies WakaTimeForUE4-main folder to Plugins, wakatime icon is not found by `Style->Set`. It's rendered just like a pink square.

Maybe there is some better way for naming or you could warn user specially in README?

**Comment by Pozitrone** [comment]
First, I am sorry I noticed it this late; luckily, it's not a huge issue that would render the plugin unusable.

I will take a look at it today evening and will try to figure something out :)
