### ISSUE TITLE
License / Copyright Notices

### ISSUE THREAD

**Issue by freezernick** [Pozitrone/WakaTimeForUE4#26]
1. It would be great if there would be a license in this repository, so you can (safely) use / extend / (... whatever the license allows) the plugin
2. There are copyright notices in the code reserving all rights to Epic Games. I guess they were meant for the default code when initializing a new plugin, but since this isn't the default code anymore they shouldn't be there at all (?)

**Comment by TheAshenWolf** [comment]
Thank you!

I have removed the copyright notices (hopefully I didn't miss any) and added the MIT license to it all.

**Comment by freezernick** [comment]
Thanks, I appreciate it
