### ISSUE TITLE
Windows cannot find 'wakatime'. Make sure you've typed the name correctly, then try again.

### ISSUE THREAD

**Issue by kayway** [Pozitrone/WakaTimeForUE4#3]
When I try to save my project [this ](https://i.imgur.com/B5hfkTC.png)error appears. Tested it with the command console typing "wakatime -h" and works fine as well as python and pip.

**Comment by Pozitrone** [comment]
Usually this error appears when you do not have WakaTime installed (or installed properly).

If you run cmd (without the admin rights) and type in `wakatime`, are you getting this result?
```
usage: wakatime [-h] [--entity FILE] [--key API_KEY] [--write]
                [--plugin PLUGIN] [--time time] [--lineno INT]
                [--cursorpos INT] [--entity-type ENTITY_TYPE]
                [--category CATEGORY] [--proxy PROXY] [--no-ssl-verify]
                [--ssl-certs-file FILE] [--project PROJECT]
                [--alternate-project PROJECT] [--language LANGUAGE]
                [--local-file FILE] [--hostname HOSTNAME] [--disable-offline]
                [--hide-file-names] [--hide-project-names]
                [--hide-branch-names] [--exclude PATH]
                [--exclude-unknown-project] [--include PATH]
                [--include-only-with-project-file] [--extra-heartbeats]
                [--log-file FILE] [--api-url URL] [--timeout SECONDS]
                [--sync-offline-activity AMOUNT] [--today] [--config FILE]
                [--config-section SECTION] [--config-read KEY]
                [--config-write KEY VALUE] [--verbose] [--version]
wakatime: error: argument --entity is required
```

Also, what is your version of Python (`python --version`) and Pip (`pip --version`)?

In my case the versions are:
`Python 3.9.4`
and `Pip 20.2.3`
and everything is working.

If everything above fits, try restarting your computer, as that can sometimes magically fix things.

Please, give me a word if you were successful :) I'll try to research some more information about it in the meantime.

**Comment by kayway** [comment]
Restarting Fixed it!! I should of tried that sorry :P. Great plugin!!

**Comment by Pozitrone** [comment]
Thank you :) I am glad it all works now ^^ Ill add this information to the readme.
