### ISSUE TITLE
BugFixed

### ISSUE THREAD

**Issue by dawnlyn** [Pozitrone/WakaTimeForUE4#31]
In UE5_Latest(Github::ue5-main)

WakaTimeForUE.cpp#L145: 
FEditorDelegates::PostSaveWorld.Remove(PostSaveWorldHandle); -> FEditorDelegates::PostSaveWorldWithContext.Remove(PostSaveWorldHandle);

WakaTimeForUE.h: 
Add #include "EditorStyleSet.h"

And

WakaTimeForUE.Build.cs:
Add "EditorStyle" Module

Because:
WakaTimeForUE.h#L145: 
FEditorStyle::GetStyleSetName()  // Error

**Comment by dawnlyn** [comment]
But：函数 'GetStyleSetName' 已被弃用，原因: 'FEditorStyle::GetStyleSetName() is deprecated, use FAppStyle::GetAppStyleSetName() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.'

**Comment by TheAshenWolf** [comment]
Thank you for your report! Replaced the deprecated methods; everything should be back to green now.
