### ISSUE TITLE
WakaTime CLI used requires an update as it is no longer compatible with the server

### ISSUE THREAD

**Issue by TheAshenWolf** [Pozitrone/WakaTimeForUE4#36]
CLI downloaded right now is 1.18.9. The latest version is 1.90.0.

Due to API changes, WakaTime now requires `waka_` prefix, which the old CLI cannot process.
This causes the elapsed time not being submitted to WakaTime servers.

Steps to be taken:
1. Replace hardcoded 1.18.9 with a latest link (as in `releases/latest`), so the plugin always downloads the latest version
    - [WakaTimeForUE.cpp#L230](https://github.com/TheAshenWolf/WakaTimeForUE/blob/2de9d294356d6141d54bb5e5ef7a0366dee32217/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L230)
    - This should help: `https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-`

2. Remove note about `waka_` prefix from README.md

3. Replace [WakaTimeForUE.cpp#L432](https://github.com/TheAshenWolf/WakaTimeForUE/blob/2de9d294356d6141d54bb5e5ef7a0366dee32217/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L432) with a dynamic call to plugin version

4. OCD hits hard. Fix [this line](https://github.com/TheAshenWolf/WakaTimeForUE/blob/2de9d294356d6141d54bb5e5ef7a0366dee32217/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L489).

I will start downloading UE5 today and will attempt a fix in the upcoming days. Please, hold tight!
Any help is appreciated, but not required.

**Comment by VerzatileDev** [comment]
The issue is that the Plugin references, which ever CLI is currently being used by your system, which is usually updated to the latest version of 1.90.  To fix the issue the WakaTime Website should be updated to expect the New CLI " 1.90 " Instead of the older version.

I have the fixed code for Unreal 5 as well, nothign too major I'd happily make a branch and test it out if you dont mind, otherwise I was in the middle of just making a new repository entierly to accomidate Unreal Engine 5 Specifically.

As I have now spent over 10 hours fixing it and reading into the documentation :D

**Comment by VerzatileDev** [comment]
> CLI downloaded right now is 1.18.9. The latest version is 1.90.0.
> 
> Due to API changes, WakaTime now requires `waka_` prefix, which the old CLI cannot process. This causes the elapsed time not being submitted to WakaTime servers.
> 
> Steps to be taken:
> 
> 1. Replace hardcoded 1.18.9 with a latest link (as in `releases/latest`), so the plugin always downloads the latest version
>    
>    * [WakaTimeForUE.cpp#L230](https://github.com/TheAshenWolf/WakaTimeForUE/blob/2de9d294356d6141d54bb5e5ef7a0366dee32217/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L230)
>    * This should help: `https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-`
> 2. Remove note about `waka_` prefix from README.md
> 
> I will start downloading UE5 today and will attempt a fix in the upcoming days. Please, hold tight!

This is the part I was looking for the past few hours I somehow missed it " https://github.com/TheAshenWolf/WakaTimeForUE/blob/2de9d294356d6141d54bb5e5ef7a0366dee32217/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L230 "

**Comment by VerzatileDev** [comment]
I'm currently changing a few things on the following Branch, https://github.com/VerzatileDev/WakaTimeForUE/tree/UE5-Update I will keep you updated.

**Comment by TheAshenWolf** [comment]
Any help is much appreciated :) I have not touched Unreal in years, so I am definitely not up to date.

Thanks a lot!

**Comment by VerzatileDev** [comment]
I have currently mentioned the issue in an email to Wakatime Support, that it requires an update to the CLI system as version 1.18.9 is no longer supported and does not exist or show up on the website. 

- Though it is possible to still download it from the Link you have there somehow, I'm not sure how but the first time I used it did download it, even though it references an empty website.


Do you happen to remember what it is based upon on ? the Version and CLI ? which is found on the website itself? 

For example:

The following command works as of currently ` " /c start "" /b "C:\Users\Verza\.wakatime\wakatime-cli-windows-amd64.exe" --entity "MyProject1" --key waka_ApiKey --project "MyProject1" --entity-type "app" --language "Unreal Engine" --plugin "unreal-wakatime/1.2.2" --category coding --write " ` , if " waka_ " is removed, but as I currently updated it for the newest version I cannot use it. 

As the One expected on the website Looks for the CLI version 1.18.9 and Version 1.2.2

Anyways enough mumbling around it, do you know how the version was updated on the website is that done manually by them or your repository ?

As the command is on this line " 	[Command += "--plugin \"unreal-wakatime/1.2.2\" "; " ](https://github.com/TheAshenWolf/WakaTimeForUE/blob/2de9d294356d6141d54bb5e5ef7a0366dee32217/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L432) " , Changing that and any other data doesnt seem to be doing anything.

**Comment by TheAshenWolf** [comment]
So, if I understand correctly, even if the command is updated to
```
" /c start "" /b "C:\Users\User\.wakatime\wakatime-cli-windows-amd64.exe" --entity "MyProject1" --key ApiKey --project "MyProject1" --entity-type "app" --language "Unreal Engine" --plugin "unreal-wakatime/1.2.5" --category coding --write "
``` 
(including the `waka_` prefix in the API key that is saved)
when using the 1.90.0 CLI, the server rejects it?

**Comment by VerzatileDev** [comment]
It does seem that the CLI version was updated somehow, by Forcing a heartbeat without the Prefix 

![image](https://github.com/TheAshenWolf/WakaTimeForUE/assets/47317248/a5cd0c91-9260-493e-ac29-f53c1f934668)


Currently it seems to work within my Status 

![image](https://github.com/TheAshenWolf/WakaTimeForUE/assets/47317248/43a192fb-0db9-4a75-a5b8-c944e48cfd34)


Seem to Reference a new CLI version, but seems that the Command does not update it to 1.2.5

**Comment by TheAshenWolf** [comment]
It might be just taking a while. 

adding `--verbose` to the command may also help to find potential issues.

**Comment by VerzatileDev** [comment]
I found out why the version and cli was acting weird, it was because there was an issue in the way I did the build in regards to the files. Now I recived the Heartbeat with the " waka_ " prefix as well as managed to change the version. 

![image](https://github.com/TheAshenWolf/WakaTimeForUE/assets/47317248/b0968d45-cd8c-4971-aa36-10a705158be1)

So that side works as Intended, Now I need to somehow Fix the mess I did with the " Cli " download, for some reason It keeps downloading 1.18.9 back each time, once I fix that that I will push the changes and hopefully refactor the code slightly. 

Which from then as I understand the update has to be merged and we or you have to let know of the " Wakatime " support team to update it as a third party Statistic globally.

- Learning as I go as I have never done plugins myself. 

Though to make it official according to their website it is best to " Transfer " the codebase to the owner of the WakaTime where they will add maintainers to that repository from which it is possible to update it and fix and etc.

**Comment by VerzatileDev** [comment]
> So, if I understand correctly, even if the command is updated to
> 
> ```
> " /c start "" /b "C:\Users\User\.wakatime\wakatime-cli-windows-amd64.exe" --entity "MyProject1" --key ApiKey --project "MyProject1" --entity-type "app" --language "Unreal Engine" --plugin "unreal-wakatime/1.2.5" --category coding --write "
> ```
> 
> (including the `waka_` prefix in the API key that is saved) when using the 1.90.0 CLI, the server rejects it?

That is my miss understanding apologies on that matter I miss-read the documentation. ( Its mostly based on the local build files generated from the plugin which defines how it acts. 

- I aint no expert, but  " get it working " - > Refactor it - > Make it nice .  Is the current goal.  ( Apologies for spamming you with messages I got a bit addicted to finding a solution to this one :D )

**Comment by TheAshenWolf** [comment]
No problem :) Now we should just sync about who is doing what, so we are not stepping on each others toes. Thanks for all the time you invested into this!

**Comment by VerzatileDev** [comment]
> No problem :) Now we should just sync about who is doing what, so we are not stepping on each others toes. Thanks for all the time you invested into this!

Awesome to hear, I think let me Invest the time to fix some areas and push the changes and we can continue to make it even better, Because I'd be interested in making the interface slightly better, maybe even adding what is being tracked and how potentially in the future. 

- Currently I think its best for me to push the changes and then if you don't mind we could both go through the changes and see what needs fixing.
- I need to as well note to myself to write proper Commit messages and statuses to better describe why and what.

 I will keep you updated, apologies if I'm stating that I want to control it for a little bit ( Honestly I haven't felt this exited for a while when programming and finding solutions :D )

**Comment by TheAshenWolf** [comment]
Works for me! Glad you are having a great time :D I have quite a lot of my plate as is with other repos, so I am really grateful for the help ❤️. My Unreal and project should be ready, so just let me know :)

**Comment by VerzatileDev** [comment]
Yeah It does seem to behave as intended almost in UE5 as well 
![image](https://github.com/TheAshenWolf/WakaTimeForUE/assets/47317248/66c2bfe3-5b26-4a21-9a3e-6fbd5998deed)

**Comment by VerzatileDev** [comment]
Took a bit of time off earlier, but currently I just use hardcoded version for the CLI

![image](https://github.com/TheAshenWolf/WakaTimeForUE/assets/47317248/be0aa789-f122-4880-80da-ceb4e10b1195)


Though I do wonder comsidering amd64 that these CLI's are specific to the system, so I assume these have to be changed or looked for depending on the system itself within the code. 

As you previously mentioned this:

[WakaTimeForUE.cpp#L230](https://github.com/TheAshenWolf/WakaTimeForUE/blob/2de9d294356d6141d54bb5e5ef7a0366dee32217/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L230)
This should help: https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-

I think the link is invalid and if it was it would get the latest, which would be included with pre-releases at least that is how I understand it. 

- Going to remove the debug logs from everywhere, remove the build files and see if anything else is messed up and fix them and test and then will Commit it, and hopefully do a pull request. <3

And Later on look to consider changes to the system that it select the correct CLI, as I have both linux and windows, and it seems that the windows work won't send heartbeats with the given CLI.


Current:
---


- [x] " waka_ " prefix works
- [x] CLI is being correctly downloaded ( Specific to version of Windows - Excludes other systems ).
- [x] Version Code as well now gets updated.

Considerations
---

- [ ] Specify a system to select CLI based on the Operating system ( Later updates hopefully ).
- [ ]  Seperate Debug into an option to disable and enable ( To avoid spamming the console of projects unessecarily ).
- [ ]  Look into updating the Plugin on the wakatime Website Through support ( After Update If approved and fixed ).
- [x]  Need to test it for both ( Engine - > Plugins /  Project -> Plugins ).

That is it for now will continue :)

- Looking to write the part of Building it for their own specific versions section within the Read.me or some other part

**Comment by TheAshenWolf** [comment]
> I think the link is invalid ...

If you replace the link that is currently there
```cpp
string URL = "https://github.com/wakatime/wakatime-cli/releases/download/v1.18.9/wakatime-cli-windows-" +
		GWakatimeArchitecture + ".zip";
```
to
```cpp
string URL = "https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-" +
		GWakatimeArchitecture + ".zip";
```
you get the correct link.

E.g.: `https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-amd64.zip`

> ... and if it was it would get the latest, which would be included with pre-releases at least that is how I understand it.  

Try going here: `https://github.com/wakatime/wakatime-cli/releases/latest`. You will see the pre-release packages are ignored.

**Comment by VerzatileDev** [comment]
Heya, I removed the other features that would be related to other changes, keeping mainly focused on the Core to update it for UE5
https://github.com/TheAshenWolf/WakaTimeForUE/pull/37 


Working build with the changes is here: https://github.com/VerzatileDev/WakaTimeForUE/releases/tag/v.1.2.5 


Any other issues to be references and done in other PRs.

If there are any issues please let me know, and if you downloaded it try testing it as well!!


And as I understand it is best to let the WakaTime Support team know of the new update, Unless they have it referenced by Latest such alike you mentioned with the CLI version <3 Thank you for that


Thank you for the journey :) Now only thing left to do is to Update it on WakaTime website End and it should be added to leaderboards and statistics correctly

**Comment by TheAshenWolf** [comment]
Pull request merged, thank you a lot for the help once again! I updated the readme to reflect the changes a bit and made a release :) 

Closing this issue!

**Comment by VerzatileDev** [comment]
Btw to mention it here as well, it is being tracked on WakaTime.

![image](https://github.com/TheAshenWolf/WakaTimeForUE/assets/47317248/f723c93a-a4c3-4e3b-a6cb-e5ab0be21068)


But it is not tracked in global leaderboards, for which you need to contact WakaTime support to setup and accomidate the new update https://wakatime.com/help/contact

support@wakatime.com
