### ISSUE TITLE
Macro redefinition warning on build

### ISSUE THREAD

**Issue by CamMerrill** [Pozitrone/WakaTimeForUE4#4]
Building a project a project with the plugin on windows generates the following warnings:

`   winnt.h(603): [C4005] 'TEXT': macro redefinition `
`  Platform.h(1082): [C4005] see previous definition of 'TEXT' `

**Desktop**
 - OS: Windows
 - Unreal Engine 4.26.2

**Additional context**
This due to the #include <windows.h> [here](https://github.com/Pozitrone/WakaTimeForUE4/blob/32f4e05e310dc7e6cac1c77d1a6fb48027cbf63a/Source/WakaTimeForUE4/Private/WakaTimeForUE4.cpp)

**Comment by Pozitrone** [comment]
Pull request #5 merged.
