### ISSUE TITLE
Plugin prevents packaging

### ISSUE THREAD

**Issue by Pozitrone** [Pozitrone/WakaTimeForUE4#6]
When plugin is enabled, all packaging fails due to "Unknown Cook Failure".

Starting the editor without the plugin successfully packages the project.

I need to look into this issue, but I do not have a viable internet connection, so it has to wait a bit.
Sorry for the inconvenience.

**Comment by simonSlamka** [comment]
Gonna take a look at this now.

**Comment by simonSlamka** [comment]
Could you post your console output during packaging with the plugin enabled, please?

**Comment by Pozitrone** [comment]
[CookingFailed.txt](https://github.com/Pozitrone/WakaTimeForUE4/files/6853497/CookingFailed.txt)

**Comment by simonSlamka** [comment]
> 
> 
> [CookingFailed.txt](https://github.com/Pozitrone/WakaTimeForUE4/files/6853497/CookingFailed.txt)

Yeah, that's the one. I'm experiencing exactly the same series of errors.

I've tried many things from which none worked, but I'm going to continue trying. We'll figure it out.

**Comment by BiosElement** [comment]
Not sure if this is useful at all, but it might be a lead: https://answers.unrealengine.com/questions/958804/how-to-exclude-editor-module-that-is-part-of-plugi.html

**Comment by Pozitrone** [comment]
I have stumbled upon this a while back too.
Sadly, we already have this setting for version 1.2.0, so the issue has to be elsewhere.

**Comment by simonSlamka** [comment]
Wow, you fixed it? Great job!
