### ISSUE TITLE
[win10] wakatime won't run without the wakatime-cli file extension (.exe)

### ISSUE THREAD

**Issue by simonSlamka** [Pozitrone/WakaTimeForUE4#8]
Hi,

I am using WakaTime in many editors and IDEs.
They have installed the official version to `~/.wakatime/wakatime-cli`
Now, the executable name within that dir is `wakatime-cli.exe`, not just `wakatime`. This way the system cannot find the executable. Removing the extension, on the other hand, causes the executable to be unrunnable. 

I'm no Windows guru, so I don't really know what to do here. Tried making an alias, like I would do in Linux, but it doesn't work. Windows's "macros" are not very efficient and don't reportedly work in batch scripts.

Ideas?

Thanks

**Comment by Pozitrone** [comment]
Good day,

if I understand correctly, that means that the command `wakatime` does not exist for you?
If that is the case, what would be the command to call a heartbeat instead?

In case it would be just an instance of "use this command instead of this one", it should not be hard to add it as an option to switch between those two, if necessary :)

**Comment by simonSlamka** [comment]
Well, I have to call the executable directly: `wakatime-cli.exe`. I've added the WakaTime dir to $PATH, so it works anywhere.
I'm going to try to do that, yeah. If it works, I would recommend adding it to the origin (your repo) so it doesn't happen to other people too.

Thanks for responding.

**Comment by Pozitrone** [comment]
It is weird that this is happening.

The whole plugin was coded on windows 10 and I never encountered said issue, but I guess it can happen ^.^
I will add it to my 1.2 roadmap, as it is currently under development already :) Thank you :)

Have a great day!

**Comment by simonSlamka** [comment]
Hold on. You possibly misunderstood what I meant originally. I already had the wakatime-cli before I got this plugin, since I am using it in other editors. I wanted to use that same binary in this plugin. That binary is called `wakatime-cli.exe`.

**Comment by Pozitrone** [comment]
Oh... well... 
Ill conduct further research regarding how it behaves and so on :) and if it is possible, I think it still would be nice to have both options ^.^

**Comment by simonSlamka** [comment]
I'll open a PR if that's not a problem for you.

**Comment by Pozitrone** [comment]
Sure, go on :)

I sadly can't look into it much today, but I promise to give it a thorough look tomorrow! ^.^

**Comment by simonSlamka** [comment]
#9 

I'll try to write a workaround around cmd, as I don't think it's the most efficient way to do this. Please test the code before merging, more in the PR description. But the conditional itself works, so there's a problem of some sort afterwards.

**Comment by Pozitrone** [comment]
using the wakatime command, you have to use cmd, there is no other way (at least I think) :)

however, using the cli directly, one should be able to use the system method to run the exe along with all the required arguments.

Also, I plan on adding a text field (much like with the api key) where you would paste the full path to the cli, so you wouldn't even have to have it in your $PATH :) 

As I said before, I will look into it thoroughly tomorrow and try to improve the plugin :)

Thank you for your contribution! ^.^

**Comment by simonSlamka** [comment]
@Pozitrone It's possible because I just did it and it's working.

Yeah, sure, take a look whenever you're free and test it for yourself. Then please let me know and I will make some additional changes. Afterwards, we can merge.

**Comment by simonSlamka** [comment]
@Pozitrone I see that you merged. Is everything working for you?

**Comment by Pozitrone** [comment]
Through the whole development of 1.2.0, I was using purely the cli. Due to this, I believe this is now working.
